/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as DisplaysRouteImport } from './routes/displays'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PlaylistsIndexRouteImport } from './routes/playlists/index'
import { Route as PlaylistsNewRouteImport } from './routes/playlists/new'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const DisplaysRoute = DisplaysRouteImport.update({
  id: '/displays',
  path: '/displays',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlaylistsIndexRoute = PlaylistsIndexRouteImport.update({
  id: '/playlists/',
  path: '/playlists/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlaylistsNewRoute = PlaylistsNewRouteImport.update({
  id: '/playlists/new',
  path: '/playlists/new',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/displays': typeof DisplaysRoute
  '/settings': typeof SettingsRoute
  '/playlists/new': typeof PlaylistsNewRoute
  '/playlists': typeof PlaylistsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/displays': typeof DisplaysRoute
  '/settings': typeof SettingsRoute
  '/playlists/new': typeof PlaylistsNewRoute
  '/playlists': typeof PlaylistsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/displays': typeof DisplaysRoute
  '/settings': typeof SettingsRoute
  '/playlists/new': typeof PlaylistsNewRoute
  '/playlists/': typeof PlaylistsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/displays' | '/settings' | '/playlists/new' | '/playlists'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/displays' | '/settings' | '/playlists/new' | '/playlists'
  id:
    | '__root__'
    | '/'
    | '/displays'
    | '/settings'
    | '/playlists/new'
    | '/playlists/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DisplaysRoute: typeof DisplaysRoute
  SettingsRoute: typeof SettingsRoute
  PlaylistsNewRoute: typeof PlaylistsNewRoute
  PlaylistsIndexRoute: typeof PlaylistsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/displays': {
      id: '/displays'
      path: '/displays'
      fullPath: '/displays'
      preLoaderRoute: typeof DisplaysRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/playlists/': {
      id: '/playlists/'
      path: '/playlists'
      fullPath: '/playlists'
      preLoaderRoute: typeof PlaylistsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/playlists/new': {
      id: '/playlists/new'
      path: '/playlists/new'
      fullPath: '/playlists/new'
      preLoaderRoute: typeof PlaylistsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DisplaysRoute: DisplaysRoute,
  SettingsRoute: SettingsRoute,
  PlaylistsNewRoute: PlaylistsNewRoute,
  PlaylistsIndexRoute: PlaylistsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
